### ISSUE TITLE
GeoPoliticalUnits

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/api_nodetest#17]
[Function](https://bitbucket.org/cei/neotomawsdata/src/a4267aed5fa2b144f8d4c887514104deebdbfe28/GetRequestHandler.vb?at=default&fileviewer=file-view-default#GetRequestHandler.vb-2523)

```
        Dim gpId As Integer = -1
        Dim gpDt As DataTable = Nothing
        'Dim htArray() As Hashtable
        Dim responseHt As Hashtable
        Dim ignoreFields As New ArrayList
        Dim format As String = request("format")
        ignoreFields.Add("PublicationID")
```
- [x] Write empty function
- [x] Write Swagger function declaration
- [x] Write response declaration
- [x] Write function

**Comment by stryker-m** [comment]
data object returned by /v2/data/GeopoliticalUnits does not match /v1 data object which is: "data":[{"GeoPoliticalID":173,"GeoPoliticalName":"Antarctica"},{"GeoPoliticalID":264,"GeoPoliticalName":"Argentina"},...

**Comment by SimonGoring** [comment]
Can you raise this in a new issue?
