### ISSUE TITLE
'apps/TaxaInDatasets' endpoint

### ISSUE THREAD

**Issue by stryker-m** [NeotomaDB/api_nodetest#23]
The [apps/TaxaInDatasets endpoint](https://bitbucket.org/cei/neotomawsdata/src/a4267aed5fa2b144f8d4c887514104deebdbfe28/GetRequestHandler.vb?at=default&fileviewer=file-view-default#GetRequestHandler.vb-214) is defined in the BitBucket repo.

- [x] Identify stored procedure dependencies
AP.GetTaxaInDatasets
- [x] Write pg function
- [x] Write empty handler function
- [x] Write Swagger function declaration
- [x] Write response declaration
- [x] Write function

**Comment by SimonGoring** [comment]
This endpoint now resolves as:

```
/v2/data/datasets/12/taxa/
```

This then maintains the cross-functionality that we've established elsewhere.
