### ISSUE TITLE
swagger documentation wasn't resolving

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/api_nodetest#39]
Going to the landing page for `api-dev` remotely was returning an error because it couldn't find the `swagger.json` file. @stryker-m

**Comment by SimonGoring** [comment]
I fixed this by editing `node/public/api-docs/index.html` and changing the reference to the remote host.

**Comment by SimonGoring** [comment]
For future reference, the line to modify was here: https://github.com/NeotomaDB/api_nodetest/blob/dev/public/api-docs/index.html#L76

**Comment by stryker-m** [comment]
Good find.  Odd we need to edit the index.html.  Seems the SwaggerUIBundle should provide a means to pass that from the config object.

**Comment by SimonGoring** [comment]
My guess is that there is a more complete fix, and that this was just lazy :)
