### ISSUE TITLE
connection to database not defined

### ISSUE THREAD

**Issue by stryker-m** [NeotomaDB/api_nodetest#41]
the app comments out the db connection.  Testing this request:  http://api-dev.neotomadb.org/v2/data/contacts/6988

returns db is not defined error.

The file app.js comments out db var.  The version of app.js does not match any commits in the repo.  @SimonGoring are you trying out some refactoring?

**Comment by SimonGoring** [comment]
I think it's something in `contacts`.  Sites works fine:

http://api-dev.neotomadb.org/v2/data/sites/2

It's because I switched to the `master` branch in api-dev from `dev`, having just made some final changes.  I'll check it out.

**Comment by stryker-m** [comment]
I see that initializing pg-promise with the connection string has been moved from the app to multiple places, one in each helper directory.  From what I understand, the connection should be initialized once globally and reused.  From the [docs](http://vitaly-t.github.io/pg-promise/index.html): "Object db represents the Database protocol with lazy connection, i.e. only the actual query methods acquire and release the connection automatically. Therefore you should create only one global/shared db object per connection details.

It is best to initialize the library and create Database in its own module, see Where should I initialize pg-promise."  Looks like we should go with this to avoid creating connections in each route helper.

You're right about contacts/:id.  The handler is defined within the queries file and there is no db connection available in that module.

**Comment by SimonGoring** [comment]
Right, my impression, and maybe this is a misunderstanding, is that this is initializing the db once and then closing it, because each call to the API is effectively a single instance of an "app", so we really are only initializing one db connection.  

I moved the initializations into each module (I think) because I was running into a problem exporting the connection from the `apps` file to the (for example) `.helpers/datasets/dataset.js` module.

**Comment by stryker-m** [comment]
We only want one pg-promise db instance in the app per user_role:db.  This instance will manage the connections used throughout the app.  Initializing multiple instances for each request handler is not what we want to do.

I added a database initialization module [here.](https://github.com/NeotomaDB/api_nodetest/commit/df0ed058cba634405b5142120f692b330a222fe3#diff-a9921a4b64cf49378fa5e0231ce67914)  Each handler should import this.
