### ISSUE TITLE
Does not accept lists of identifiers

### ISSUE THREAD

**Issue by jpjenk** [NeotomaDB/api_nodetest#53]
Occs endpoint and presumably ohers only returns the final identifier in a list. eg. siteid=923,101 will only return records for siteid 101.

This is an ELC requirement.

**Comment by SimonGoring** [comment]
The implementation in `v2` is generally:

```
v2/data/sites/12,23,24,12,54/datasets
```

I will check other queries where comma separated lists are passed in.

**Comment by SimonGoring** [comment]
I think this is because the limit is by default 25.

I just tried http://localhost:3000/v2/data/occurrence/?siteid=12,13,14&offset=2000&limit=999

on my local build and I got a record for one of the other sites.

**Comment by SimonGoring** [comment]
This now works:

```
http://api-dev.neotomadb.org/v2/data/occurrence/?siteid=12,13,14&offset=2000&limit=999
```
