### ISSUE TITLE
Age returns for datasets

### ISSUE THREAD

**Issue by jpjenk** [NeotomaDB/api_nodetest#61]
Age information is not included in either sites or more importantly datasets return despite the purported ability to search records based on min/max age ranges in these endpoints.

**Comment by SimonGoring** [comment]
Fixed in commit abe911242a77f87d79a6840d74a28913d01ff1ad.  Note that ongoing changes mean the addition of v2.0 soon.

**Comment by jpjenk** [comment]
Checked. This fix has been merged.
