### ISSUE TITLE
Cross reference pub ID's with old Neotoma API (some may be missing)

### ISSUE THREAD

**Issue by jpjenk** [NeotomaDB/api_nodetest#65]
Example cases:

http://api.neotomadb.org/v1/data/publications?pubid=1412

http://api-dev.neotomadb.org/v2.0/data/publications?pubid=1412

Empty return for new API so something is suspicious here.

**Comment by SimonGoring** [comment]
There is a different way of doing this:
http://api.neotomadb.org/v1/data/publications/1412

The other method should work, but for some reason the publication 1412 isn't working, and I'm not sure why.

**Comment by SimonGoring** [comment]
Okay, it was a problem with the default query, some of the publications (and 1412 for example) are not associated with datasets explicitly, so the inner join failed.

https://github.com/NeotomaDB/api_nodetest/commit/e84b236594c1aaf2cc6c83dc47137cbe70a34228

**Comment by SimonGoring** [comment]
Fixed with Pull Request #67
